### ISSUE TITLE
iPhone 7 Plus 9,4 not supported

### ISSUE THREAD

**Issue by d386538** [xerub/extra_recipe#13]
Many saying iPhone 7 Plus now worked for their i7+, and so I gave extra_recipe a try.

Apperantly, the extra_recipe does say:

> iPhone 7 (Plus) 10 up to 10.1.1

But extra_recipe just closed after I hit "go", after multiple try, it still doesn't work...

Maybe the the one worked are iPhone9,2 and not iPhone9,4??

**Comment by razer86** [comment]
Using it on a 7+ (iPhone9,4) just fine here. Takes a few goes, but gets there

**Comment by d386538** [comment]
I already did multiple try, 20 times, including restart the phone are try again from scratch.
The app doesn't seemed to be crashed, it acted more like it just exit.

**Comment by Abbasoo** [comment]
- Sign out from iCloud
- Put your iPhone in Airplane Mode
- Hit "go"

**Comment by d386538** [comment]
I see someone tired 30 times,,,
https://www.reddit.com/r/jailbreak/comments/6f59m0/question_should_extra_recipe_take_upwards_of_20/

maybe i should do 50 before let go....

**Comment by razer86** [comment]
Had a random crash today, closed all apps in the task switcher, airplane mode, took 4 goes to jailbreak

**Comment by va2ron1** [comment]
If you previous have another version of the jailbreak, could be a installed Tweak (already happen to me).
Run mach_portal+b3, uninstall the tweak from Cydia. Then reboot and try extra_recipe

**Comment by xerub** [comment]
iPhone 7 Plus was reported as working up to 10.1.1
