### ISSUE TITLE
News widget stop working

### ISSUE THREAD

**Issue by mtshare** [xerub/extra_recipe#14]
**News** widget stopped working after jailbreaking with **extra_recipe**.
No problems when on **yalu + mach_portal**.
Keep saying **No Stories**

I'm on iPhone 7 10.1.1

**Comment by xerub** [comment]
Please test with a ssh-only version (aka the master branch). I don't support cydia -- it's there only by public request. If the problem persists with master, I'll look into it.

**Comment by johnsoninnyc** [comment]
mtshare do you have Flex 3 installed ?   if so does disabling or uninstalling it fix the issue?   Same for Safari & Web targeting tweaks.

**Comment by mtshare** [comment]
@xerub Same with the master branch (ssh-only).
@johnsoninnyc News doesn't work neither in SafeMode nor in un-jailbreaken state (rebooting in normal mode).

**Comment by mtshare** [comment]
News are back again. Seems temporary problem maybe tweak related.
