### ISSUE TITLE
Does extra_recipe can breaks daemons?

### ISSUE THREAD

**Issue by mr-f0xx** [xerub/extra_recipe#35]
i have a huge battery drain even in non-substrate mode by the daemons EscrowSecurityalert, mobilassetd useractivityd & wcd which sometimes uses 100 % of my cpu.. So I wonder if this could be related to extra_recipe?

**Comment by xerub** [comment]
No. But even if it does break any of your thing, you get to keep all the pieces.

THE PROGRAM IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

Joking aside, I don't really know. My suggestion is to run the ssh-only version (master branch) for a while and see if you experience those anomalies. I do not provide support for tweaks, or anything Cydia-related for that matter.
