### ISSUE TITLE
/ not mounted as read-write

### ISSUE THREAD

**Issue by nayu-codes** [xerub/extra_recipe#4]
Read-only filesystem :/

**Comment by Mila432** [comment]
poor kid

**Comment by Cryptiiiic** [comment]
Use cake to remount as rw

**Comment by 2600box** [comment]
run `mount -u -w /dev/disk0s1s1` as root to mount filesystem rw

**Comment by coolstar** [comment]
Fixed in 2b26369750b7e303aec3cc3bcfe4588039db2ff4. This thread should be closed
