### ISSUE TITLE
Can test for iphone 7 plus 

### ISSUE THREAD

**Issue by B0ngL0rd** [xerub/extra_recipe#5]
If you need any testers for iphone 7 plus hmu :)

**Comment by xerub** [comment]
Which iOS version?

**Comment by B0ngL0rd** [comment]
10.2 iphone 7 plus

**Comment by B0ngL0rd** [comment]
And 10.2.1 ipad pro 9.7

**Comment by xerub** [comment]
Then no. iPhone 7(plus) is supported only up to 10.1.1
