### ISSUE TITLE
Failed to allocate fixed mapping: (os/kern) no space available

### ISSUE THREAD

**Issue by codexx420** [xerub/extra_recipe#52]
Hello,

recently, I lost my compiled **working** version of extra_recipe for my iPad Air 2. (it worked 1 month ago with the compiled version I had since extra_recipe is out)
Sadly, I have no mac and my friends either have no macs also or don't want to share their macs for installing xcode, debugging etc. I can use the mac from my work - I'm very limited here. 

I don't know how to get a compiled ipa in xCode (note: I do not own a paid developer subscription). Google doesn't help. When I try to debug extra_recipe on my ipad, I'm getting "Failed to allocate fixed mapping: (os/kern) no space available" in jailbreak.c line 213. 

I am a programmer, but this level is too high for me. Any help would be awesome.

**Comment by FatalPunisher88** [comment]
same here

**Comment by FatalPunisher88** [comment]
luckily i have saved my original compiled extra recipe ipa when luca had the github project up before the ipa

**Comment by codexx420** [comment]
It would be awesome if you can share your compiled IPA + some information.
( do you also use an **iPad Air 2** (mine is 16gb, Cellular) / And your compiled version is working?)

**Comment by codexx420** [comment]
Okay. After hundred of tries. I got yalu102 beta7 working and I also could catch the working compiled version of extra_recipe for my iPad Air 2. 
you can find anything that works on my ipad here: https://github.com/codexx420/compiled-102-jailbreak just a secure backup solution for people who may need it in future as I couldn't find it.
